const fs=require('fs');const path=require('path');
const base=__dirname;
const CORAL='#D2453C',CREAM='#FFF1DC',INK='#1D1815',MUTED='#705E54',YELLOW='#F2DC58';
const home='https://nobrenparfum.lt/lt/',search='https://nobrenparfum.lt/lt/paieska';
const campaign='2026_09_24_meginelis_i_buteliuka';
const subject='Kuris mėginėlis dingo pirmas?';
const preheader='Tavo favoritas laukia pilname 30 ml buteliuke – nuo 22 €.';
const assetCommit='380a7ed8722b249b7ecb7b5e6e46a6b7b719c2bc';
const cdn='https://raw.githubusercontent.com/elaiskai/nobren-email-assets/'+assetCommit+'/campaigns/2026-09-meginelis-i-buteliuka/';
const esc=s=>String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;');
const track=(url,key)=>url+'?utm_source=klaviyo&utm_medium=email&utm_campaign='+campaign+'&utm_content='+key;
const copy={
 C54:{audience:'Moterims',notes:'Ananasai · jazminai · ąžuolo samanos',description:'Šviesus, rafinuotas vaisių ir žiedų šleifas.'},
 T3:{audience:'Moterims',notes:'Jazminai · kašmyras · baltas gintaras',description:'Šiltas, jausmingas ir lengvai atpažįstamas.'},
 C1:{audience:'Moterims',notes:'Citrina · rausvieji pipirai · jazminai',description:'Žaisminga gaiva su minkšta vanilės pabaiga.'},
 A25:{audience:'Vyrams',notes:'Bergamotė · jūros gaiva · smilkalai',description:'Gaivus, tvirtas ir elegantiškai dūminis.'},
 E4:{audience:'Vyrams',notes:'Kardamonas · kaštonai · vanilė',description:'Šiltas, saldus ir jaukus vakaro favoritas.'},
 H21:{audience:'Vyrams',notes:'Imbieras · levandos · oda',description:'Prieskonių energija ir sodri odos pabaiga.'}
};
const products=JSON.parse(fs.readFileSync(path.join(base,'products.json'),'utf8')).map(p=>({...p,...copy[p.code]}));
for(const p of products){if(!copy[p.code]||p.quantity<=0||p.available_for_order!=='1'||p.price_amount<21||!Object.values(p.attributes).some(a=>a.name==='30ml')||!Object.values(p.attributes).some(a=>a.name==='Su buteliuku'))throw Error('Recheck selected product '+p.code);}
if(products.length!==6)throw Error('Expected six in-stock products');
const table=(body,attrs='')=>`<table role="presentation" cellpadding="0" cellspacing="0" border="0" ${attrs}>${body}</table>`;
const button=(url,label,key,{bg=INK,color=CREAM}={})=>table(`<tr><td align="center" bgcolor="${bg}" style="background-color:${bg}!important;text-align:center;mso-padding-alt:16px 24px;"><a href="${esc(track(url,key))}" target="_blank" style="display:block;padding:16px 24px;font:800 12px/16px Arial,Helvetica,sans-serif;letter-spacing:.8px;text-align:center;color:${color}!important;text-decoration:none;mso-padding-alt:0;">${label} &nbsp;↗</a></td></tr>`,'align="center" style="margin:0 auto;"');
const imageRow=(file,w,h,alt,bg,url,key)=>`<tr><td bgcolor="${bg}" style="background-color:${bg}!important;padding:0;font-size:0;line-height:0;">${url?`<a href="${esc(track(url,key))}" target="_blank">`:''}<img src="assets/${file}" width="${w}" height="${h}" alt="${esc(alt)}" style="display:block;width:100%;max-width:${w}px;height:auto;border:0;">${url?'</a>':''}</td></tr>`;
const css=`
#nobren-sample .ns-brand{display:block!important;opacity:1!important;filter:none!important;mix-blend-mode:normal!important}
#nobren-sample a[x-apple-data-detectors]{color:inherit!important;text-decoration:none!important}
@media screen and (max-width:620px){.ns-outer{padding:0!important}.ns-wrap{width:100%!important}.ns-pad{padding-left:24px!important;padding-right:24px!important}.ns-intro{padding-bottom:32px!important}.ns-intro-title{font-size:34px!important;line-height:38px!important}.ns-copy{font-size:15px!important;line-height:24px!important}.ns-steps{padding:16px 17px 29px!important}.ns-step-num{font-size:30px!important;line-height:34px!important}.ns-step-title{font-size:11px!important;line-height:15px!important}.ns-step-copy{font-size:10px!important;line-height:15px!important}.ns-gap{width:15px!important}.ns-grid{padding:10px 16px 24px!important}.ns-title-cell{height:57px!important}.ns-product-title{font-size:20px!important;line-height:25px!important}.ns-notes{font-size:11px!important;line-height:17px!important}.ns-description{font-size:12px!important;line-height:18px!important}.ns-description-cell{height:65px!important}.ns-price{font-size:24px!important;line-height:29px!important}.ns-product-button{font-size:10px!important;letter-spacing:0!important;padding:14px 5px!important}.ns-closing-title{font-size:36px!important;line-height:41px!important}.ns-footer-cell{display:block!important;width:100%!important;text-align:left!important}.ns-footer-nav{padding-top:18px!important;text-align:left!important}}
@media screen and (max-width:350px){.ns-pad{padding-left:20px!important;padding-right:20px!important}.ns-steps{padding-left:13px!important;padding-right:13px!important}.ns-gap{width:10px!important}.ns-step-num{font-size:27px!important}.ns-step-copy{font-size:9px!important;line-height:14px!important}.ns-grid{padding-left:13px!important;padding-right:13px!important}.ns-product-title{font-size:18px!important;line-height:23px!important}.ns-price{font-size:22px!important}.ns-closing-title{font-size:32px!important;line-height:37px!important}}
`;
const productCell=p=>`<td class="ns-product" valign="top" style="padding:0;vertical-align:top;">${table(`
<tr><td style="padding:0 0 8px;border-bottom:2px solid ${INK};"><p style="font-size:11px;line-height:16px;letter-spacing:1.2px;font-weight:800;color:${INK};">${p.code} <span style="font-weight:400;color:${MUTED};">/ ${p.audience.toUpperCase()}</span></p></td></tr>
<tr><td style="padding:10px 0 0;font-size:0;line-height:0;"><a href="${esc(track(p.url,p.code.toLowerCase()+'_image'))}" target="_blank"><img src="assets/products/${p.code.toLowerCase()}.jpg" width="244" height="277" alt="Nobren ${p.displayName} ${p.code}" style="display:block;width:100%;max-width:244px;height:auto;border:0;"></a></td></tr>
<tr><td class="ns-title-cell" height="64" valign="top" style="height:64px;padding:10px 0 0;"><h3 class="ns-product-title" style="font-size:24px;line-height:29px;letter-spacing:-.5px;color:${INK};font-weight:800;">${p.displayName}</h3></td></tr>
<tr><td height="44" valign="top" style="height:44px;padding:8px 0 0;"><p class="ns-notes" style="font-size:12px;line-height:18px;font-weight:700;color:${INK};">${p.notes}</p></td></tr>
<tr><td class="ns-description-cell" height="58" valign="top" style="height:58px;padding:8px 0 0;"><p class="ns-description" style="font-size:13px;line-height:20px;color:${MUTED};">${p.description}</p></td></tr>
<tr><td style="padding:13px 0 0;"><p class="ns-price" style="font-size:27px;line-height:32px;letter-spacing:-.4px;font-weight:800;color:${CORAL};white-space:nowrap;">${p.price.replace(/\s+€/,'&nbsp;€')}</p><p style="font-size:10px;line-height:17px;color:${MUTED};">30 ml · su buteliuku</p></td></tr>
<tr><td style="padding:13px 0 0;">${table(`<tr><td bgcolor="${INK}" align="center" style="background-color:${INK}!important;text-align:center;mso-padding-alt:15px 6px;"><a class="ns-product-button" href="${esc(track(p.url,p.code.toLowerCase()+'_cta'))}" target="_blank" style="display:block;padding:15px 6px;font-size:11px;line-height:15px;letter-spacing:.3px;font-weight:800;color:${CREAM}!important;text-align:center;text-decoration:none;mso-padding-alt:0;">PERŽIŪRĖTI PREKĘ</a></td></tr>`,'width="100%" style="width:100%;"')}</td></tr>
`,'width="100%" style="width:100%;table-layout:fixed;"')}</td>`;
const productRows=[];for(let i=0;i<products.length;i+=2)productRows.push(`<tr><td class="ns-grid" style="padding:10px 36px 26px;">${table(`<tr>${productCell(products[i])}<td class="ns-gap" width="28" style="width:28px;font-size:0;line-height:0;">&nbsp;</td>${productCell(products[i+1])}</tr>`,'width="100%" style="width:100%;table-layout:fixed;"')}</td></tr>`);
const step=(n,title,text)=>`<td valign="top" style="padding:0;vertical-align:top;"><p class="ns-step-num" style="font-size:34px;line-height:38px;font-weight:800;color:${CORAL};">${n}</p><p class="ns-step-title" style="padding-top:8px;font-size:12px;line-height:16px;letter-spacing:.5px;font-weight:800;color:${INK};">${title}</p><p class="ns-step-copy" style="padding-top:7px;font-size:11px;line-height:17px;color:${MUTED};">${text}</p></td>`;
const rows=`
${imageRow('brand/logo-strip-samples.png',600,85,'Nobren Parfum LT',CORAL,home,'logo')}
${imageRow('hero/hero-final-samples.jpg',600,750,'Kuris mėginėlis dingo pirmas? Pilnas 30 ml buteliukas nuo 22 €.',CORAL,search,'hero')}
<tr><td class="ns-pad ns-intro" align="center" bgcolor="${CORAL}" style="background-color:${CORAL}!important;padding:0 48px 40px;text-align:center;">${table(`
<tr><td align="center" style="padding:0;text-align:center;"><p style="font-size:10px;line-height:16px;letter-spacing:1.6px;font-weight:800;color:${CREAM};">JEI VIENĄ PURŠKEI DAŽNIAU — ATSAKYMĄ JAU ŽINAI</p></td></tr>
<tr><td align="center" style="padding:18px 0 0;text-align:center;"><h2 class="ns-intro-title" style="font-size:39px;line-height:44px;letter-spacing:-1.3px;font-weight:800;color:${INK};text-align:center;">Mėginėlis buvo<br>tik pradžia.</h2></td></tr>
<tr><td align="center" style="padding:16px 0 0;text-align:center;"><p class="ns-copy" style="font-size:16px;line-height:25px;color:#FFF8EE;text-align:center;">Jeigu vieną kvapą nešiojaisi su savimi, naudojai dažniau ar saugojai paskutiniam papurškimui — favoritą jau radai.</p></td></tr>
<tr><td align="center" style="padding:25px 0 0;text-align:center;">${button(search,'IEŠKOTI SAVO KODO','intro_cta',{bg:INK,color:CREAM})}</td></tr>
`,'width="100%" style="width:100%;"')}</td></tr>
${imageRow('hero/intro-tail-samples.png',600,75,'',CORAL,null,null)}
<tr><td class="ns-products" bgcolor="${CREAM}" style="background-color:${CREAM}!important;padding:0;">${table(`
<tr><td class="ns-pad" style="padding:23px 36px 12px;"><p style="font-size:10px;line-height:16px;letter-spacing:1.5px;font-weight:800;color:${CORAL};">3 ŽINGSNIAI IKI FAVORITO</p><h2 style="padding-top:11px;font-size:34px;line-height:39px;letter-spacing:-1px;font-weight:800;color:${INK};">Nuo kodo iki 30 ml.</h2></td></tr>
<tr><td class="ns-steps" style="padding:16px 36px 34px;">${table(`<tr>${step('01','PAIMK MĖGINĖLĮ','Kodas yra ant jo etiketės.')}<td class="ns-gap" width="24" style="width:24px;font-size:0;line-height:0;">&nbsp;</td>${step('02','ĮVESK KODĄ','Pavyzdžiui: T3, C1 ar E4.')}<td class="ns-gap" width="24" style="width:24px;font-size:0;line-height:0;">&nbsp;</td>${step('03','RINKIS 30 ML','Pilnas buteliukas nuo 22 €.')}</tr>`,'width="100%" style="width:100%;table-layout:fixed;"')}</td></tr>
<tr><td class="ns-pad" style="padding:22px 36px 18px;border-top:2px solid ${INK};"><p style="font-size:10px;line-height:16px;letter-spacing:1.5px;font-weight:800;color:${CORAL};">GAL ATPAŽINSI SAVO?</p><h2 style="padding-top:10px;font-size:34px;line-height:39px;letter-spacing:-1px;font-weight:800;color:${INK};">Šeši kodai atminčiai sužadinti.</h2><p style="padding-top:12px;font-size:14px;line-height:22px;color:${MUTED};">Tavo favoritas gali būti visai kitas — svarbiausia kodas ant mėginėlio.</p></td></tr>
${productRows.join('\n')}
<tr><td class="ns-pad" style="padding:2px 36px 31px;"><p style="font-size:10px;line-height:16px;color:${MUTED};">Kainos patikrintos 2026-09-22. C1 pristatomas naujo dizaino buteliuke. Produktų nuotraukos — iš Nobren parduotuvės.</p></td></tr>
`,'width="100%" style="width:100%;"')}</td></tr>
<tr><td class="ns-closing" bgcolor="${INK}" style="background-color:${INK}!important;padding:0;">${table(`
<tr><td class="ns-pad" align="center" style="padding:42px 48px 8px;text-align:center;"><p style="font-size:10px;line-height:16px;letter-spacing:1.6px;font-weight:800;color:${YELLOW};text-align:center;">TAVO TESTAS BAIGTAS</p><h2 class="ns-closing-title" style="padding-top:17px;font-size:42px;line-height:47px;letter-spacing:-1.5px;font-weight:800;color:${CREAM};text-align:center;">Mėginėlis baigėsi.<br><span style="color:${CORAL};">Įspūdis liko.</span></h2><p class="ns-copy" style="padding-top:17px;font-size:15px;line-height:24px;color:#D9CABB;text-align:center;">Kodas ant mėginėlio — trumpiausias kelias iki kvapo, kurį jau išbandei ant savo odos.</p></td></tr>
<tr><td class="ns-pad" style="padding:24px 46px 3px;">${table(`<tr><td width="72" align="center" style="width:72px;border:2px solid ${CORAL};padding:14px 4px;text-align:center;"><p style="font-size:11px;line-height:14px;font-weight:800;color:${CREAM};">5 ML</p></td><td style="padding:0 14px;"><div style="height:2px;background:${CORAL};font-size:0;line-height:0;">&nbsp;</div></td><td width="96" align="center" bgcolor="${CORAL}" style="width:96px;background-color:${CORAL}!important;padding:14px 4px;text-align:center;"><p style="font-size:11px;line-height:14px;font-weight:800;color:${INK};">30 ML</p></td></tr>`,'width="100%" style="width:100%;"')}</td></tr>
<tr><td class="ns-pad" align="center" style="padding:27px 42px 43px;text-align:center;">${button(search,'RASTI PILNĄ BUTELIUKĄ','closing_cta',{bg:CORAL,color:INK})}</td></tr>
<tr><td class="ns-pad" style="padding:25px 36px 31px;border-top:1px solid #4A403A;">${table(`<tr><td class="ns-footer-cell" valign="top" style="padding:0;vertical-align:top;"><a href="${esc(home)}" style="font-size:13px;line-height:22px;font-weight:800;color:${CORAL};text-decoration:none;">nobrenparfum.lt</a><p style="padding-top:7px;font-size:10px;line-height:17px;color:#B9AAA0;">MB „Nobren parfum“<br>Gintaro g. 56, Vydmantai<br>© 2026 Nobren Parfum</p></td><td class="ns-footer-cell ns-footer-nav" align="right" valign="top" style="padding:0;text-align:right;vertical-align:top;font-size:11px;line-height:25px;color:#B9AAA0;"><a href="https://nobrenparfum.lt/lt/parduotuves" style="color:#B9AAA0;text-decoration:underline;">Kontaktai</a> &nbsp;·&nbsp; <a href="https://nobrenparfum.lt/lt/info/privatumo-politika" style="color:#B9AAA0;text-decoration:underline;">Privatumas</a><br><a href="{% unsubscribe_link %}" style="display:inline-block;line-height:30px;color:#B9AAA0;text-decoration:underline;">Atsisakyti prenumeratos</a></td></tr>`,'width="100%" style="width:100%;"')}</td></tr>
`,'width="100%" style="width:100%;"')}</td></tr>`;
const contentTemplate=`<div style="display:none!important;font-size:1px;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;mso-hide:all;">${preheader}</div>${table(`<tr><td class="ns-outer" align="center" style="padding:24px 12px;text-align:center;"><!--[if mso]><table role="presentation" width="600" align="center" cellpadding="0" cellspacing="0" border="0"><tr><td><![endif]-->${table(rows,`id="nobren-sample" class="ns-wrap" align="center" width="600" bgcolor="${CREAM}" style="width:100%;max-width:600px;margin:0 auto;table-layout:fixed;background-color:${CREAM}!important;text-align:left;font-family:Arial,Helvetica,sans-serif;color:${INK};"`)}<!--[if mso]></td></tr></table><![endif]--></td></tr>`,'width="100%" bgcolor="#E8E1D8" style="width:100%;background-color:#E8E1D8!important;"')}`;
const hardened=contentTemplate
 .replace(/<(p|h[1-3])\b([^>]*)style="([^"]*)"/g,(_,tag,attrs,style)=>{const align=(style.match(/(?:^|;)\s*text-align:([^;]+)/)||[])[1]||'inherit';return '<'+tag+attrs+'style="padding:0;font-family:Arial,Helvetica,sans-serif;color:inherit;text-transform:none;font-style:normal;'+style+'margin:0!important;text-align:'+align+'!important;"';})
 .replace(/<table\b([^>]*)>/g,(_,attrs)=>'<table'+(attrs.includes('style="')?attrs.replace('style="','style="border-collapse:collapse;border-spacing:0;mso-table-lspace:0pt;mso-table-rspace:0pt;'):attrs+' style="border-collapse:collapse;border-spacing:0;mso-table-lspace:0pt;mso-table-rspace:0pt;"')+'>')
 .replace(/<td\b([^>]*)>/g,(_,attrs)=>'<td'+(attrs.includes('style="')?attrs:attrs+' style="padding:0;"')+'>')
 .replace(/<td\b([^>]*)style="([^"]*)"/g,(_,attrs,style)=>{const align=(attrs.match(/\balign="([^"]+)"/)||[])[1]||'inherit';return '<td'+attrs+'style="text-align:'+align+';'+(/background-color:/.test(style)?style:('background-color:transparent!important;'+style))+'"';});
const html=`<!doctype html><html lang="lt"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="x-apple-disable-message-reformatting"><meta name="format-detection" content="telephone=no,address=no,email=no,date=no"><meta name="color-scheme" content="light"><meta name="supported-color-schemes" content="light"><title>Kuris mėginėlis dingo pirmas? · Nobren</title><!--[if mso]><noscript><xml><o:OfficeDocumentSettings xmlns:o="urn:schemas-microsoft-com:office:office"><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml></noscript><![endif]--><style>html,body{margin:0!important;padding:0!important;width:100%!important}${css}</style></head><body style="margin:0;padding:0;background-color:#E8E1D8;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;">${hardened}</body></html>`;
const hosted=s=>s.replace(/src="(assets\/[^"]+)"/g,(_,asset)=>'src="'+cdn+asset+'"');
const block='<style>'+css+'</style>\n'+hosted(hardened).replace('padding:24px 12px;','padding:0;');
fs.writeFileSync(path.join(base,'newsletter.html'),html);fs.writeFileSync(path.join(base,'newsletter-klaviyo.html'),hosted(html));fs.writeFileSync(path.join(base,'klaviyo-block.html'),block);fs.writeFileSync(path.join(base,'klaviyo-block.txt'),block);
const plain=`Tema: ${subject}\nPreview line: ${preheader}\n\nKURIS MĖGINĖLIS DINGO PIRMAS?\n\nMėginėlis buvo tik pradžia.\nJeigu vieną kvapą nešiojaisi su savimi, naudojai dažniau ar saugojai paskutiniam papurškimui — favoritą jau radai.\nIeškoti savo kodo: ${track(search,'intro_cta')}\n\nNUO KODO IKI 30 ML\n1. Paimk mėginėlį — kodas yra ant etiketės.\n2. Įvesk kodą paieškoje.\n3. Rinkis pilną 30 ml buteliuką nuo 22 €.\n\nŠEŠI KODAI ATMINTI SUŽADINTI\n\n${products.map(p=>`${p.displayName} · ${p.code} · ${p.audience}\n${p.notes}\n${p.description}\n${p.price} / 30 ml, su buteliuku\nPeržiūrėti prekę: ${track(p.url,p.code.toLowerCase()+'_cta')}`).join('\n\n')}\n\nMĖGINĖLIS BAIGĖSI. ĮSPŪDIS LIKO.\nKodas ant mėginėlio — trumpiausias kelias iki kvapo, kurį jau išbandei ant savo odos.\nRasti pilną buteliuką: ${track(search,'closing_cta')}\n\nMB „Nobren parfum“\nGintaro g. 56, Vydmantai\nhttps://nobrenparfum.lt/lt/\nKontaktai: https://nobrenparfum.lt/lt/parduotuves\nPrivatumas: https://nobrenparfum.lt/lt/info/privatumo-politika\nAtsisakyti prenumeratos: {% unsubscribe_link %}\n`;
fs.writeFileSync(path.join(base,'newsletter.txt'),plain);console.log(JSON.stringify({subject,preheader,products:products.length,htmlBytes:Buffer.byteLength(hosted(html)),blockBytes:Buffer.byteLength(block)}));
