const {chromium}=require('playwright'),sharp=require('sharp'),fs=require('fs'),path=require('path');const {pathToFileURL}=require('url');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 if(process.argv.includes('--logo')||process.argv.includes('--hero')){const hero=process.argv.includes('--hero'),page=await browser.newPage({viewport:{width:1200,height:hero?800:144},deviceScaleFactor:1});await page.goto(pathToFileURL(path.join(__dirname,hero?'hero-compose.html':'logo-compose.html')).href);await page.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0));const buffer=await page.screenshot();if(hero)await sharp(buffer).removeAlpha().jpeg({quality:94,chromaSubsampling:'4:4:4'}).toFile(path.join(__dirname,'assets/hero/hero-home-v1.jpg'));else await sharp(buffer).removeAlpha().png().toFile(path.join(__dirname,'assets/logo-strip.png'));await page.close();console.log(hero?'Saved hero composite':'Saved opaque logo strip');return;}
 const hosted=process.argv.includes('--hosted'),reports=[];
 for(const [name,width]of [['desktop',820],['mobile',390],['mobile-320',320]]){
 const page=await browser.newPage({viewport:{width,height:850},deviceScaleFactor:1,colorScheme:'light'});await page.goto(pathToFileURL(path.join(__dirname,hosted?'newsletter-klaviyo.html':'newsletter.html')).href);await page.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0));
 const report=await page.evaluate(()=>{const button=document.querySelector('.ns26-button'),wrap=document.querySelector('.ns26-wrap'),ctas=[...document.querySelectorAll('.ns26-product-button')],prices=[...document.querySelectorAll('.ns26-product-price')],copies=[...document.querySelectorAll('.ns26-product-copy')];return{width:innerWidth,height:document.body.scrollHeight,container:wrap.getBoundingClientRect().width,overflow:[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1||e.getBoundingClientRect().left< -1).map(e=>e.tagName),buttonText:button.textContent,buttonHeight:button.getBoundingClientRect().height,href:button.getAttribute('href'),unsubscribe:document.querySelector('.ns26-unsubscribe').getAttribute('href'),allPresentation:[...document.querySelectorAll('table')].every(t=>t.getAttribute('role')==='presentation'),products:[...document.querySelectorAll('.ns26-product-title')].map((p,i)=>({name:p.textContent,price:prices[i].textContent,descriptionGap:prices[i].getBoundingClientRect().top-copies[i].getBoundingClientRect().bottom,buttonY:ctas[i].getBoundingClientRect().top,button:ctas[i].textContent,url:ctas[i].href})),images:[...document.images].map(i=>({src:i.getAttribute('src'),width:i.naturalWidth})),text:wrap.innerText};});
 if(report.overflow.length||report.buttonHeight<44||!report.allPresentation||report.images.length!==4||report.products.length!==2||report.products.some(p=>!p.price.includes('18,90')||p.descriptionGap>32||p.button!=='PERŽIŪRĖTI PREKĘ')||Math.abs(report.products[0].buttonY-report.products[1].buttonY)>1||(hosted&&(!report.href.includes("{% update_property_link 'nobren_keep_emails_20261001' 'yes'")||report.unsubscribe!=='{% unsubscribe_link %}')))throw Error(JSON.stringify(report));
 await page.screenshot({path:path.join(__dirname,`preview-${name}.png`),fullPage:true});if(name!=='mobile-320')await page.locator('.ns26-products').screenshot({path:path.join(__dirname,`preview-products-${name}.png`)});reports.push({name,...report});console.log(JSON.stringify({name,width,height:report.height,overflow:report.overflow,gaps:report.products.map(p=>p.descriptionGap)}));await page.close();}
 fs.writeFileSync(path.join(__dirname,'qa',hosted?'hosted.json':'local.json'),JSON.stringify(reports,null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
