const fs=require('fs');const path=require('path');
const base=__dirname;
const BLUE='#173DCB',CREAM='#F6EEC9',INK='#182142',MUTED='#586078';
const home='https://nobrenparfum.lt/lt/',collection=home+'nisiniai-kvepalai';
const campaign='2026_09_kuo_tu_kvepi';
const subject='Atsiprašau… kuo tu kvepi?';
const preheader='Aštuoni kvapai, aštuoni skirtingi atsakymai. Kuris bus tavo?';
const assetCommit='64dcf86200360cca326f516a3ae00d8fb8acc26a';
const cdn='https://raw.githubusercontent.com/elaiskai/nobren-email-assets/'+assetCommit+'/campaigns/2026-09-kuo-tu-kvepi/';
const esc=s=>String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;');
const track=(url,key)=>url+'?utm_source=klaviyo&utm_medium=email&utm_campaign='+campaign+'&utm_content='+key;
const copy={
 T21:{tag:'VYŠNIŲ INTRIGA',notes:'Vyšnios · kartieji migdolai · tonka',description:'Tirštas vyšnių saldumas su karčiu migdolų akcentu.',audience:'Unisex'},
 B5:{tag:'ŠILTAS ATSAKYMAS',notes:'Konjakas · cinamonas · ąžuolas',description:'Konjako ir cinamono duetas su šiltu medienos fonu.',audience:'Unisex'},
 I6:{tag:'ROŽĖ SU CHARAKTERIU',notes:'Rožė · rožiniai pipirai · vanilė',description:'Ryški rožė, pipirų kibirkštis ir švelni vanilės pabaiga.',audience:'Unisex'},
 P20:{tag:'VAISIAI IR ŽIEDAI',notes:'Ličiai · rabarbarai · turkiška rožė',description:'Vaisių gaiva susitinka su gėlėmis ir lengva rūgštele.',audience:'Moterims'},
 X3:{tag:'PASLAPTINGAS GYLIS',notes:'Levandos · kedras · agarmedis',description:'Levandų pradžia, medienos šiluma ir sodrus agarmedis.',audience:'Unisex'},
 S1:{tag:'SALDI GAIVA',notes:'Citrusai · baltasis muskusas · vanilė',description:'Citrusų šviesa, minkštas muskusas ir vanilės saldumas.',audience:'Unisex'},
 T6:{tag:'ŠVELNI TRAUKA',notes:'Kokosas · kriaušių žiedai · juodmedis',description:'Švelnūs žiedai su kokoso saldumu ir medienos šiluma.',audience:'Unisex'},
 N7:{tag:'VANILĖS KIBIRKŠTIS',notes:'Vanilė · mėlynasis imbieras · bergamotė',description:'Gaivus imbieras ir bergamotė susilieja su šilta vanile.',audience:'Unisex',displayCode:'N7*'}
};
const products=JSON.parse(fs.readFileSync(path.join(base,'products.json'),'utf8')).map((p,i)=>({...p,...copy[p.code],num:String(i+1).padStart(2,'0')}));
for(const p of products){if(p.quantity<=0||p.price_amount!==(p.code==='N7'?35:29.9)||!Object.values(p.attributes).some(a=>a.name==='30ml')||!Object.values(p.attributes).some(a=>a.name==='Su buteliuku'))throw Error('Recheck selected product '+p.code);}
const table=(body,attrs='')=>`<table role="presentation" cellpadding="0" cellspacing="0" border="0" ${attrs}>${body}</table>`;
const button=(url,label,key,{bg=BLUE,color=CREAM,full=false}={})=>table(`<tr><td align="center" bgcolor="${bg}" style="background-color:${bg};text-align:center;mso-padding-alt:16px 20px;"><a href="${esc(track(url,key))}" target="_blank" style="display:block;padding:16px 20px;font:700 12px/16px Arial,Helvetica,sans-serif;letter-spacing:.8px;text-align:center;color:${color};text-decoration:none;mso-padding-alt:0;">${label} &nbsp;↗</a></td></tr>`,`${full?'width="100%"':'align="center"'} style="${full?'width:100%;':'margin:0 auto;'}"`);
const imageRow=(file,w,h,alt,bg,url,key,extra='')=>`<tr><td bgcolor="${bg}" style="background-color:${bg};padding:0;font-size:0;line-height:0;">${url?`<a href="${esc(track(url,key))}" target="_blank">`:''}<img src="assets/${file}" width="${w}" height="${h}" alt="${esc(alt)}" ${extra} style="display:block;width:100%;max-width:${w}px;height:auto;border:0;">${url?'</a>':''}</td></tr>`;
const css=`
#nobren-question a[x-apple-data-detectors]{color:inherit!important;text-decoration:none!important}
@media screen and (max-width:620px){.nq-outer{padding:0!important}.nq-wrap{width:100%!important}.nq-pad{padding-left:24px!important;padding-right:24px!important}.nq-header{padding:18px 24px 8px!important}.nq-mast{font-size:9px!important;line-height:15px!important;letter-spacing:.8px!important}.nq-intro-title{font-size:30px!important;line-height:34px!important}.nq-intro-copy{font-size:15px!important;line-height:24px!important}.nq-grid{padding:10px 16px 16px!important}.nq-gap{width:18px!important}.nq-product-title{font-size:21px!important;line-height:26px!important;letter-spacing:-.5px!important}.nq-tag{font-size:9px!important;line-height:15px!important;letter-spacing:.6px!important}.nq-notes{font-size:12px!important;line-height:18px!important}.nq-description{font-size:13px!important;line-height:20px!important}.nq-description-cell{height:72px!important}.nq-price{font-size:25px!important;line-height:30px!important}.nq-product-button{font-size:11px!important;letter-spacing:.1px!important;padding:15px 7px!important}.nq-section-title{font-size:30px!important;line-height:34px!important}.nq-footer-cell{display:block!important;width:100%!important;text-align:left!important}.nq-footer-nav{padding-top:18px!important;text-align:left!important}}
@media screen and (max-width:350px){.nq-pad{padding-left:20px!important;padding-right:20px!important}.nq-header{padding-left:20px!important;padding-right:20px!important}.nq-mast{font-size:8px!important;letter-spacing:.3px!important}.nq-intro-title{font-size:26px!important;line-height:32px!important}.nq-grid{padding-left:14px!important;padding-right:14px!important}.nq-gap{width:14px!important}.nq-product-title{font-size:18px!important;line-height:24px!important}.nq-tag{font-size:8px!important;letter-spacing:.35px!important}.nq-price{font-size:23px!important}.nq-section-title{font-size:27px!important;line-height:31px!important}}
`;
const productCell=(p)=>`<td class="nq-product" valign="top" style="padding:0;vertical-align:top;">${table(`
<tr><td style="padding:0 0 9px;border-bottom:1px solid #DCE2F3;"><p class="nq-tag" style="font-size:10px;line-height:16px;letter-spacing:.9px;font-weight:700;color:${BLUE};">${p.num} / ${p.tag}</p></td></tr>
<tr><td style="padding:12px 0 5px;font-size:0;line-height:0;"><a href="${esc(track(p.url,p.code.toLowerCase()+'_image'))}" target="_blank"><img src="assets/products/${p.code.toLowerCase()}.jpg" width="244" height="277" alt="Nobren ${p.displayName} ${p.displayCode||p.code} – oficiali buteliuko ir dėžutės nuotrauka" style="display:block;width:100%;max-width:244px;height:auto;border:0;"></a></td></tr>
<tr><td style="padding:8px 0 0;"><p style="font-size:10px;line-height:16px;letter-spacing:1px;font-weight:700;color:${BLUE};">${p.displayCode||p.code} <span style="font-weight:400;letter-spacing:.3px;color:${MUTED};">/ ${p.audience.toUpperCase()}</span></p></td></tr>
<tr><td style="padding:5px 0 0;"><h3 class="nq-product-title" style="font-size:25px;line-height:30px;letter-spacing:-.7px;color:${INK};font-weight:700;">${p.displayName}</h3></td></tr>
<tr><td height="47" valign="top" style="height:47px;padding:8px 0 0;"><p class="nq-notes" style="font-size:13px;line-height:19px;font-weight:700;color:${INK};">${p.notes}</p></td></tr>
<tr><td class="nq-description-cell" height="65" valign="top" style="height:65px;padding:10px 0 0;"><p class="nq-description" style="font-size:14px;line-height:21px;color:${MUTED};">${p.description}</p></td></tr>
<tr><td style="padding:15px 0 0;"><p class="nq-price" style="font-size:28px;line-height:34px;letter-spacing:-.6px;font-weight:700;color:${BLUE};white-space:nowrap;">${p.price.replace(/\s+€/,'&nbsp;€')}</p><p style="font-size:11px;line-height:18px;color:${MUTED};">30 ml · su buteliuku</p></td></tr>
<tr><td style="padding:14px 0 0;">${table(`<tr><td bgcolor="${BLUE}" align="center" style="background-color:${BLUE};text-align:center;mso-padding-alt:16px 10px;"><a class="nq-product-button" href="${esc(track(p.url,p.code.toLowerCase()+'_cta'))}" target="_blank" style="display:block;padding:16px 10px;font-size:12px;line-height:16px;letter-spacing:.9px;font-weight:700;color:#FFFFFF;text-align:center;text-decoration:none;mso-padding-alt:0;">PERŽIŪRĖTI PREKĘ</a></td></tr>`,'width="100%" style="width:100%;"')}</td></tr>
`,'width="100%" style="width:100%;table-layout:fixed;"')}</td>`;
const productRows=[];
for(let i=0;i<products.length;i+=2)productRows.push(`<tr><td class="nq-grid" bgcolor="#FFFFFF" style="background-color:#FFFFFF;padding:12px 36px 25px;">${table(`<tr>${productCell(products[i])}<td class="nq-gap" width="28" style="width:28px;font-size:0;line-height:0;">&nbsp;</td>${productCell(products[i+1])}</tr>`,'width="100%" style="width:100%;table-layout:fixed;"')}</td></tr>`);
const rows=`
<tr><td class="nq-header" bgcolor="${BLUE}" style="background-color:${BLUE};padding:22px 32px 6px;">${table(`<tr><td width="141" style="width:141px;padding:0;">${table(`<tr><td bgcolor="${CREAM}" style="background-color:${CREAM};padding:10px 12px;"><a href="${esc(track(home,'logo'))}" target="_blank"><img src="assets/brand/logo.png" width="116" height="46" alt="Nobren Parfum LT" style="display:block;width:116px;height:auto;border:0;"></a></td></tr>`)}</td><td class="nq-mast" align="right" style="padding-left:15px;text-align:right;font-size:10px;line-height:17px;letter-spacing:1.3px;color:${CREAM};font-weight:700;">KVAPAS —<br>POKALBIO PRADŽIA</td></tr>`,'width="100%" style="width:100%;"')}</td></tr>
${imageRow('hero/hero-final.jpg',600,750,'Kuo tu kvepi? Nobren Lost Cherry T21 su vyšniomis ir chromo kabutėmis sodriai mėlynoje scenoje.',BLUE,products[0].url,'hero')}
<tr><td class="nq-pad nq-intro" align="center" bgcolor="${BLUE}" style="background-color:${BLUE};padding:0 48px 36px;text-align:center;">${table(`
<tr><td align="center" style="padding:0;text-align:center;"><p style="font-size:10px;line-height:16px;letter-spacing:1.4px;color:#DCE4FF;text-align:center;">KADRE — LOST CHERRY · T21</p></td></tr>
<tr><td align="center" style="padding:22px 0 0;text-align:center;"><h1 class="nq-intro-title" style="font-size:36px;line-height:40px;letter-spacing:-1px;font-weight:700;color:${CREAM};text-align:center;">Vienas klausimas.<br>Aštuoni geri atsakymai.</h1></td></tr>
<tr><td align="center" style="padding:16px 0 0;text-align:center;"><p class="nq-intro-copy" style="font-size:16px;line-height:25px;color:#FFFFFF;text-align:center;">Vyšnios, rožės ar sodri mediena?<br>Atrask kvapą pagal savo charakterį.</p></td></tr>
<tr><td align="center" style="padding:24px 0 0;text-align:center;">${button(collection,'RASTI SAVO ATSAKYMĄ','intro_cta',{bg:CREAM,color:BLUE})}</td></tr>
`,'width="100%" style="width:100%;"')}</td></tr>
${imageRow('hero/intro-tail.png',600,56,'',BLUE,null,null,'role="presentation"')}
<tr><td class="nq-pad" bgcolor="#FFFFFF" style="background-color:#FFFFFF;padding:20px 36px 26px;"><p style="font-size:10px;line-height:16px;letter-spacing:1.6px;font-weight:700;color:${BLUE};">AŠTUONI SKIRTINGI CHARAKTERIAI</p><h2 class="nq-section-title" style="padding-top:12px;font-size:35px;line-height:39px;letter-spacing:-1.2px;font-weight:700;color:${INK};">Koks būtų<br>tavo atsakymas?</h2><p style="padding-top:13px;font-size:14px;line-height:23px;color:${MUTED};">Nuo <strong style="color:${INK};">29,90 € / 30 ml.</strong> Išsirink artimiausią sau.</p></td></tr>
${productRows.join('\n')}
<tr><td class="nq-pad" bgcolor="#FFFFFF" style="background-color:#FFFFFF;padding:0 36px 16px;"><p style="font-size:10px;line-height:16px;color:${MUTED};">I6 ir X3 pristatomi naujo dizaino buteliukuose. Produktų nuotraukos — iš Nobren parduotuvės.</p></td></tr>
${imageRow('closing/dialogue.png',600,440,'Galimas pokalbio tęsinys. „Kuo tu kvepi?“ — „Nobren. O kuris? Paslaptis.“',CREAM,null)}
<tr><td class="nq-pad nq-ending" bgcolor="${CREAM}" align="center" style="background-color:${CREAM};padding:0 42px 35px;text-align:center;">${table(`
<tr><td align="center" style="padding:0;text-align:center;"><p style="font-size:17px;line-height:26px;color:${INK};text-align:center;">Pirmiausia išsirink sau.<br>Atsakymą sugalvosi vėliau.</p></td></tr>
<tr><td align="center" style="padding:23px 0 0;text-align:center;">${button(collection,'IŠSIRINK SAVO KVAPĄ','closing_cta')}</td></tr>
`,'width="100%" style="width:100%;"')}</td></tr>
<tr><td class="nq-pad" bgcolor="${CREAM}" style="background-color:${CREAM};padding:24px 36px 30px;border-top:1px solid #D8D0A9;">${table(`<tr><td class="nq-footer-cell" valign="top" style="padding:0;vertical-align:top;"><a href="${esc(home)}" style="font-size:13px;line-height:22px;font-weight:700;color:${BLUE};text-decoration:none;">nobrenparfum.lt</a><p style="padding-top:7px;font-size:10px;line-height:17px;color:${MUTED};">MB „Nobren parfum“<br>Gintaro g. 56, Vydmantai<br>© 2026 Nobren Parfum</p></td><td class="nq-footer-cell nq-footer-nav" align="right" valign="top" style="padding:0;text-align:right;vertical-align:top;font-size:11px;line-height:25px;color:${MUTED};"><a href="https://nobrenparfum.lt/lt/parduotuves" style="color:${MUTED};text-decoration:underline;">Kontaktai</a> &nbsp;·&nbsp; <a href="https://nobrenparfum.lt/lt/info/privatumo-politika" style="color:${MUTED};text-decoration:underline;">Privatumas</a><br><a href="{% unsubscribe_link %}" style="display:inline-block;line-height:30px;color:${MUTED};text-decoration:underline;">Atsisakyti prenumeratos</a></td></tr>`,'width="100%" style="width:100%;"')}</td></tr>`;
const contentTemplate=`<div style="display:none!important;font-size:1px;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;mso-hide:all;">${preheader}</div>
${table(`<tr><td class="nq-outer" align="center" style="padding:24px 12px;text-align:center;"><!--[if mso]><table role="presentation" width="600" align="center" cellpadding="0" cellspacing="0" border="0"><tr><td><![endif]-->${table(rows,`id="nobren-question" class="nq-wrap" align="center" width="600" bgcolor="#FFFFFF" style="width:100%;max-width:600px;margin:0 auto;table-layout:fixed;background-color:#FFFFFF;text-align:left;font-family:Arial,Helvetica,sans-serif;color:${INK};"`)}<!--[if mso]></td></tr></table><![endif]--></td></tr>`,'width="100%" bgcolor="#ECEEF4" style="width:100%;background-color:#ECEEF4;"')}`;
const hardened=contentTemplate
 .replace(/<(p|h[1-3])\b([^>]*)style="([^"]*)"/g,(_,tag,attrs,style)=>{const align=(style.match(/(?:^|;)\s*text-align:([^;]+)/)||[])[1]||'inherit';return '<'+tag+attrs+'style="padding:0;font-family:Arial,Helvetica,sans-serif;color:inherit;text-transform:none;font-style:normal;'+style+'margin:0!important;text-align:'+align+'!important;"';})
 .replace(/<table\b([^>]*)>/g,(_,attrs)=>'<table'+(attrs.includes('style="')?attrs.replace('style="','style="border-collapse:collapse;border-spacing:0;mso-table-lspace:0pt;mso-table-rspace:0pt;'):attrs+' style="border-collapse:collapse;border-spacing:0;mso-table-lspace:0pt;mso-table-rspace:0pt;"')+'>')
 .replace(/<td\b([^>]*)>/g,(_,attrs)=>'<td'+(attrs.includes('style="')?attrs:attrs+' style="padding:0;"')+'>')
 .replace(/<td\b([^>]*)style="([^"]*)"/g,(_,attrs,style)=>{const align=(attrs.match(/\balign="([^"]+)"/)||[])[1]||'inherit';return '<td'+attrs+'style="font-family:Arial,Helvetica,sans-serif;text-align:'+align+';'+style+'"';});
const html=`<!doctype html><html lang="lt"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="x-apple-disable-message-reformatting"><meta name="format-detection" content="telephone=no,address=no,email=no,date=no"><meta name="color-scheme" content="light"><meta name="supported-color-schemes" content="light"><title>Kuo tu kvepi? · Nobren</title><!--[if mso]><noscript><xml><o:OfficeDocumentSettings xmlns:o="urn:schemas-microsoft-com:office:office"><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml></noscript><![endif]--><style>html,body{margin:0!important;padding:0!important;width:100%!important}${css}</style></head><body style="margin:0;padding:0;background-color:#ECEEF4;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;">${hardened}</body></html>`;
const hosted=s=>s.replace(/src="(assets\/[^"]+)"/g,(_,asset)=>'src="'+cdn+asset+'"');
const block='<style>'+css+'</style>\n'+hosted(hardened).replace('padding:24px 12px;','padding:0;');
fs.writeFileSync(path.join(base,'newsletter.html'),html);fs.writeFileSync(path.join(base,'newsletter-klaviyo.html'),hosted(html));fs.writeFileSync(path.join(base,'klaviyo-block.html'),block);fs.writeFileSync(path.join(base,'klaviyo-block.txt'),block);
const plain=`Tema: ${subject}\nPreview line: ${preheader}\n\nNOBREN — KUO TU KVEPI?\n\nVienas klausimas. Aštuoni geri atsakymai.\nVyšnios, rožės ar sodri mediena?
Atrask kvapą pagal savo charakterį.\nRasti savo atsakymą: ${track(collection,'intro_cta')}\n\nKOKS BŪTŲ TAVO ATSAKYMAS?\n\n${products.map(p=>`${p.num}. ${p.displayName} · ${p.displayCode||p.code} · ${p.audience}\n${p.notes}\n${p.description}\n${p.price} / 30 ml, su buteliuku\nPeržiūrėti prekę: ${track(p.url,p.code.toLowerCase()+'_cta')}`).join('\n\n')}\n\nI6 ir X3 pristatomi naujo dizaino buteliukuose.\n\nGALIMAS POKALBIO TĘSINYS\n— Kuo tu kvepi?\n— Nobren. O kuris? Paslaptis.\n\nPirmiausia išsirink sau. Atsakymą sugalvosi vėliau.\nIšsirink savo kvapą: ${track(collection,'closing_cta')}\n\nMB „Nobren parfum“\nGintaro g. 56, Vydmantai\nhttps://nobrenparfum.lt/lt/\nKontaktai: https://nobrenparfum.lt/lt/parduotuves\nPrivatumas: https://nobrenparfum.lt/lt/info/privatumo-politika\nAtsisakyti prenumeratos: {% unsubscribe_link %}\n`;
fs.writeFileSync(path.join(base,'newsletter.txt'),plain);console.log(JSON.stringify({subject,preheader,products:products.length,htmlBytes:Buffer.byteLength(hosted(html)),blockBytes:Buffer.byteLength(block)}));
