const fs=require('fs');const path=require('path');const root=__dirname;
process.on('exit',()=>{require('./research/update-notes.cjs');const f=path.join(root,'campaign-notes.txt');let n=fs.readFileSync(f,'utf8');n=n.replace('gyva antraštė ir šeši trumpi tekstai iš abiejų mėginėlių ant padėklo nuotraukos pusių','gyva antraštė ir vienas vientisas vizualas su šešiais į pačią nuotrauką integruotais tekstais');fs.writeFileSync(f,n+'\nNauja aktyvi bloko iliustracija: assets/benefits-text-v2.jpg. Prompt ir šaltiniai: research/benefits-text-v2.txt. Atskiri šoniniai HTML tekstai pašalinti.\n');});
const selections=require('./research/selected-reviews.json');
const products=[
{id:'saldus',title:'TOP SALDŪS',copy:'Mėgstantiems saldesnius aromatus. Išbandykite penkis kvapus ir pasirinkite, kuris patinka labiausiai.',quote:'Kvapai gan ryškus ir i prabangesne puse :)',author:'Kristina',button:'RENKUOSI SALDŽIUS'},
{id:'gaivus',title:'TOP GAIVŪS',copy:'Ieškantiems gaivesnio kvapo. Penki mėginėliai, kuriuos galėsite palyginti neskubėdami.',quote:'Negaliu išskirti nė vieno kvapo. Visi kerintys, neerzinantys, jei reiktų rinktis vieną būtų sunku.',author:'Eugenija',button:'RENKUOSI GAIVIUS'},
{id:'stiprus',title:'TOP STIPRŪS',copy:'Mėgstantiems intensyvesnius aromatus. Atraskite savo pasirinkimą iš penkių skirtingų kvapų.',button:'RENKUOSI STIPRIUS'},
{id:'prabanga',title:'TOP PRABANGA',copy:'Medienos, rytietiškų prieskonių ir citrusų kompozicijos. Penki mėginėliai naujiems atradimams.',button:'ATRASKITE PRABANGĄ'},
{id:'virsune',title:'TOP VIRŠŪNĖ',copy:'Penki perkamiausi kvapai viename rinkinyje. Palyginkite juos ir atraskite savo favoritą.',button:'PERŽIŪRĖTI RINKINĮ'},
{id:'rekomenduoja',title:'NOBREN REKOMENDUOJA',copy:'Komandos atrinkti mažiau atrasti aromatai. Tiems, kurie nori išbandyti ką nors naujo.',button:'ATRASKITE ATRINKTUS KVAPUS'},
{id:'top10',title:'TOP 10',count:10,copy:'Dešimt nišinių aromatų po 5 ml. Daugiau skirtingų kvapų viename rinkinyje.',button:'PATIKRINTI PRIEINAMUMĄ',notice:'Prieinamumą patikrinkite produkto puslapyje.'}
].map(p=>{
 const data=JSON.parse(fs.readFileSync(path.join(root,'research',p.id+'.json')));
 const selection=selections[p.id];
 const reviews=JSON.parse(fs.readFileSync(path.join(root,'research',p.id+'-reviews.json')));
 const review=reviews.find(r=>r.id===selection?.reviewId);
 if(!review||review.entityId!==data.id||!review.content.includes(selection.quote)||/[-–—−]/.test(selection.quote))throw Error('Invalid review source: '+p.id);
 return {...p,data,quote:selection.quote,author:review.displayName};
});
const esc=s=>s.replaceAll('&','&amp;').replaceAll('"','&quot;');
const link=(url,tag)=>esc(url+(url.includes('?')?'&':'?')+'utm_source=klaviyo&utm_medium=email&utm_campaign=20261006_megineliai_10&utm_content='+tag);
const category='https://nobrenparfum.lt/lt/megineliu-rinkiniai';
const cta=(label,url,tag)=>`<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td align="center" bgcolor="#111111"><a data-cta="true" href="${link(url,tag)}" style="display:block;padding:17px 12px;color:#ffffff;font:700 13px/18px Arial,sans-serif;letter-spacing:1px;text-decoration:none;text-align:center;">${label}</a></td></tr></table>`;
const text=(s,size=16)=>`<p style="margin:0;color:#111111;font:400 ${size}px/1.6 Arial,sans-serif;">${s}</p>`;
let body=`<div style="display:none;max-height:0;overflow:hidden;mso-hide:all;">Visi 7 mėginėlių rinkiniai su 10 % nuolaida. Išsirinkite savo kvapų kryptį.</div><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="width:100%;background:#f2f1ef;"><tr><td align="center"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="width:100%;max-width:600px;background:#ffffff;">
<tr><td align="center" style="padding:26px 24px 24px;"><a href="${link('https://nobrenparfum.lt/','logo')}"><img src="assets/logo.png" width="138" alt="Nobren Parfum" style="display:block;width:138px;max-width:100%;height:auto;border:0;"></a></td></tr>
<tr><td align="center" style="padding:4px 24px 10px;"><p style="margin:0;color:#111111;font:12px/20px Arial,sans-serif;letter-spacing:3px;">MĖGINĖLIŲ RINKINIAMS</p><h1 style="margin:14px 0 16px;color:#111111;font:400 39px/1.08 Arial,sans-serif;letter-spacing:-1px;text-align:center;">ATRASKITE SAVO<br>KVAPĄ PIGIAU</h1><p style="margin:0 0 16px;color:#111111;font:400 36px/1.2 Georgia,serif;">10 % nuolaida</p>${text('Pirmiausia išbandykite.<br>Tada rinkitės didelį buteliuką.')}</td></tr>
<tr><td style="padding:14px 40px 4px;">${cta('ATRASKITE MĖGINĖLIŲ RINKINIUS',category,'hero_cta')}</td></tr>
<tr><td><a href="${link(category,'hero_image')}"><img src="assets/hero.jpg" width="600" alt="Nobren mėginėlių rinkinys ir sidabriniai kvapų mėginėliai" style="display:block;width:100%;height:auto;border:0;"></a></td></tr>
<tr><td class="benefit-panel" align="center" style="padding:34px 0 12px;"><p style="margin:0 0 9px;color:#111111;font:12px/20px Arial,sans-serif;letter-spacing:3px;">DAUGIAU KVAPŲ.</p><h2 style="margin:0 12px 26px;color:#111111;font:400 29px/1.12 Arial,sans-serif;">MAŽIAU SPĖLIONIŲ.</h2><a href="${link(category,'benefit_image')}"><img src="assets/benefits-text-v2.jpg" width="600" alt="Skirtingi aromatai. Po 5 ml išbandymui. Patogu pasiimti. Bandykite ant odos. Palyginkite kvapus. Atraskite favoritą." style="display:block;width:100%;max-width:600px;height:auto;border:0;"></a></td></tr>
<tr><td align="center" style="padding:18px 28px 12px;">${text('Nereikia rinktis vien iš aprašymo. Išbandykite kelis kvapus namuose ir atraskite, kuris jums patinka.')}</td></tr><tr><td style="padding:8px 40px 30px;">${cta('IŠBANDYKITE SU 10 % NUOLAIDA',category,'benefit_cta')}</td></tr>
<tr><td align="center" style="padding:24px 24px 30px;"><p style="margin:0 0 12px;color:#111111;font:11px/20px Arial,sans-serif;letter-spacing:3px;">7 RINKINIAI JŪSŲ ATRADIMAMS</p><h2 style="margin:0 0 18px;color:#111111;font:400 28px/1.15 Arial,sans-serif;">KOKIUS KVAPUS<br>NORITE IŠBANDYTI?</h2>${text('Pasirinkite patinkančią kryptį. Rinkiniuose rasite 5 arba 10 kvapų po 5 ml. Galimus variantus peržiūrėkite produkto puslapyje.')}</td></tr>`;
for(const p of products){body+=`<tr><td style="padding:0 20px 28px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-top:1px solid #dedbd6;"><tr><td style="padding-top:22px;text-align:center;font-size:0;">
<div style="display:inline-block;width:100%;max-width:230px;vertical-align:middle;"><a href="${link(p.data.url,p.id+'_image')}"><img src="assets/${p.id}.jpg" width="210" alt="Mėginėlių rinkinys ${p.title}, ${p.count||5} kvapai po 5 ml" style="display:block;width:100%;max-width:210px;height:auto;margin:0 auto;border:0;"></a></div>
<div style="display:inline-block;width:100%;max-width:290px;vertical-align:middle;text-align:left;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding:18px 10px;"><p style="margin:0 0 9px;color:#111111;font:11px/18px Arial,sans-serif;letter-spacing:2px;">${p.count===10?'10 KVAPŲ':'5 KVAPAI'} PO 5 ML</p><h3 style="margin:0 0 12px;color:#111111;font:400 26px/1.15 Arial,sans-serif;">${p.title}</h3>${text(p.copy,15)}<p style="margin:18px 0;color:#111111;font:400 25px/32px Arial,sans-serif;">${p.data.price} <span style="font-size:15px;text-decoration:line-through;">${p.data.regular_price}</span></p>${cta(p.button,p.data.url,p.id+'_cta')}${p.notice?'<p style="margin:10px 0 0;color:#111111;font:12px/18px Arial,sans-serif;">'+p.notice+'</p>':''}</td></tr></table></div>
</td></tr>${p.quote?`<tr><td style="padding:20px 16px;background:#f5f4f1;">${text('„'+p.quote+'“',15)}<p style="margin:10px 0 0;color:#111111;font:12px/18px Arial,sans-serif;">${p.author} · <a href="${link(p.data.url,p.id+'_review')}#idTabRevws" style="color:#111111;">Atsiliepimo ištrauka</a></p></td></tr>`:''}</table></td></tr>`;}
body+=`<tr><td align="center" style="padding:28px 28px 18px;background:#f5f4f1;"><h2 style="margin:0 0 16px;color:#111111;font:400 28px/1.15 Arial,sans-serif;">PIRMIAUSIA MĖGINĖLIS.<br>TADA JŪSŲ FAVORITAS.</h2>${text('Išbandykite kvapą ant odos, panešiokite dieną ir palyginkite su kitais. Didelį buteliuką rinkitės tada, kai jau žinote, kuris jums patinka.')}</td></tr><tr><td style="padding:8px 32px 32px;background:#f5f4f1;">${cta('IŠSIRINKTI RINKINĮ SU NUOLAIDA',category,'closing_cta')}</td></tr>
<tr><td align="center" style="padding:26px 24px;background:#ffffff;">${text('NOBREN PARFUM',13)}<p style="margin:10px 0;color:#111111;font:12px/20px Arial,sans-serif;">Nuolaida taikoma mėginėlių rinkiniams.<br>Galutinę kainą ir rinkinio variantą patikrinkite produkto puslapyje.</p><p style="margin:14px 0 0;color:#111111;font:12px/20px Arial,sans-serif;">{{ organization.full_address }}<br><a href="{% unsubscribe_link %}" style="color:#111111;">Atsisakyti naujienlaiškių</a></p></td></tr></table></td></tr></table>`;
// Match Nobren website and campaign c08, retaining email-safe fallbacks.
body=body.replaceAll('Arial,sans-serif',"'Roboto',Arial,Helvetica,sans-serif").replaceAll('Georgia,serif',"'Oswald',Arial,Helvetica,sans-serif");
body=body.replace(/<h([123]) style="([^"]*)"/g,(_,level,style)=>`<h${level} style="${style.replace("'Roboto'","'Oswald'").replace('letter-spacing:-1px','letter-spacing:0.3px')}"`);
const fontStyles=`<style>@import url('https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;700&family=Roboto:wght@400;700&display=swap');</style>`;
fs.writeFileSync(path.join(root,'klaviyo-block.html'),fontStyles+body);fs.writeFileSync(path.join(root,'klaviyo-block.txt'),fontStyles+body);
fs.writeFileSync(path.join(root,'newsletter.html'),'<!doctype html><html lang="lt"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mėginėlių rinkiniams 10 % nuolaida</title>'+fontStyles+'</head><body style="margin:0;padding:0;">'+body+'</body></html>');
fs.writeFileSync(path.join(root,'campaign-notes.txt'),`PERŽIŪROS JUODRAŠTIS, NESIŲSTI SU LOKALIAIS VAIZDŲ ADRESAIS\nSiuntimas: 2026-10-06, siuntimas nesuplanuotas.\nTema: Mėginėlių rinkiniams 10 % nuolaida\nPeržiūros tekstas: Penki kvapai po 5 ml. Išsirinkite savo rinkinį už 22,50 €.\n\nFaktai tikrinti 2026-10-05 oficialiuose produktų puslapiuose. Visi trys rinkiniai 25,00 € → 22,50 €, sandėlio likučiai teigiami. Moterims ir vyrams yra atskiri variantai. Nuolaidos kodas nereikalingas pagal rodomas kainas.\n\nAtsiliepimai yra tikslios Kristinos ir Eugenijos ištraukos iš atitinkamų produktų puslapių. Rašyba išsaugota. Nekuriami reitingai ir neišgalvojami klientai. Šaltiniai bei pilni duomenys research aplanke.\n\nPilno dydžio kvapų blokas dar neįtrauktas: reikia patvirtinti dabartinę rinkinių sudėtį. Seni nuotraukų kodai ir atsiliepimai nėra patikimas dabartinės sudėties įrodymas.\n\nHero sugeneruotas iš oficialios TOP SALDŪS nuotraukos pagal vartotojo šviesaus DUPE THEORY laiško kompoziciją. Tai stilizuotas vaizdas, ne papildomų mėginėlių komplektacijos pažadas.\n\nPrieš siuntimą: įkelti assets į viešą HTTPS hostingą ir pakeisti santykinius src; patvirtinti pilno dydžio kvapus; pakartoti QA galutinei versijai; išsiųsti tikrą Klaviyo testą. Naudoti tik prenumeratorių, kuriems leidžiama siųsti rinkodarą, bazę. GitHub niekas nepublikuota.\n`);
